version: '3.8'

services:
  # 主要网站服务
  cosco-website:
    build: .
    container_name: cosco-logistics-website
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - cosco-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 监控服务（可选）
  monitoring:
    image: nginx:alpine
    container_name: cosco-monitoring
    ports:
      - "8081:80"
    volumes:
      - ./monitoring:/usr/share/nginx/html
    networks:
      - cosco-network
    profiles:
      - monitoring

  # 数据库服务（可选，用于高级功能）
  database:
    image: mysql:8.0
    container_name: cosco-database
    environment:
      MYSQL_ROOT_PASSWORD: cosco123456
      MYSQL_DATABASE: cosco_logistics
      MYSQL_USER: cosco_user
      MYSQL_PASSWORD: cosco_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cosco-network
    profiles:
      - database

  # Redis缓存服务（可选）
  redis:
    image: redis:7-alpine
    container_name: cosco-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cosco-network
    profiles:
      - cache

  # 负载均衡器（可选，用于多实例）
  loadbalancer:
    image: nginx:alpine
    container_name: cosco-loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer.conf:/etc/nginx/nginx.conf
    networks:
      - cosco-network
    profiles:
      - loadbalancer

networks:
  cosco-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: