version: '3.8'

services:
  cosco-website:
    build: .
    container_name: cosco-logistics-website
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - cosco-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  cosco-network:
    driver: bridge

volumes:
  cosco-logs: